package bazi

import (
	"encoding/json"
	"fmt"
	"os"
	"testing"
	"time"

	"liki-engine/internal/engine/ganzhi"
	"liki-engine/internal/engine/tianwen"
)

// baziGoldenCase is one case from testdata/bazi_golden.json,
// generated by lunar-typescript (6tail) — the authoritative bazi golden source.
type baziGoldenCase struct {
	Name   string  `json:"name"`
	Solar  string  `json:"solar"`
	TZ     int     `json:"tz"`
	Lon    float64 `json:"lon"`
	Gender string  `json:"gender"`
	Pillars struct {
		Nian string `json:"nian"`
		Yue  string `json:"yue"`
		Ri   string `json:"ri"`
		Shi  string `json:"shi"`
	} `json:"pillars"`
	DaYun struct {
		StartYearAfter int      `json:"start_year_after"`
		Forward        bool     `json:"forward"`
		Steps          []string `json:"steps"`
	} `json:"da_yun"`
	SanYuan struct {
		TaiYuan  string `json:"tai_yuan"`
		MingGong string `json:"ming_gong"`
		ShenGong string `json:"shen_gong"`
	} `json:"san_yuan"`
}

// loadBaziGolden reads the lunar-typescript generated golden cases.
func loadBaziGolden(t *testing.T) []baziGoldenCase {
	t.Helper()
	b, err := os.ReadFile("testdata/bazi_golden.json")
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	var cases []baziGoldenCase
	if err := json.Unmarshal(b, &cases); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	return cases
}

// TestBaziGolden_AllLayers verifies 四柱/大运/三元 (命宫/身宫/胎元) against
// lunar-typescript golden. 覆盖：常规/立春边界/晚子时/早子时/闰月/海外。
func TestBaziGolden_AllLayers(t *testing.T) {
	for _, gc := range loadBaziGolden(t) {
		t.Run(gc.Name, func(t *testing.T) {
			tt, err := time.Parse("2006-01-02T15:04:05", gc.Solar)
			if err != nil {
				t.Fatalf("parse solar %q: %v", gc.Solar, err)
			}
			// 对齐 lunar：公历时间直接排盘（不校经度），晚子时不提前换日
			st := tianwen.SolarTime(tt)
			g := ganzhi.Male
			if gc.Gender == "female" {
				g = ganzhi.Female
			}
			c := ComputeChart(st, g)
			fc := ComputeFullChart(c)

			// 四柱
			gotPillars := fmt.Sprintf("%s%s %s%s %s%s %s%s",
				c.Nian.Gan, c.Nian.Zhi, c.Yue.Gan, c.Yue.Zhi,
				c.Ri.Gan, c.Ri.Zhi, c.Shi.Gan, c.Shi.Zhi)
			wantPillars := fmt.Sprintf("%s %s %s %s",
				gc.Pillars.Nian, gc.Pillars.Yue, gc.Pillars.Ri, gc.Pillars.Shi)
			if gotPillars != wantPillars {
				t.Errorf("四柱 = %s, want %s", gotPillars, wantPillars)
			}

			// 大运首步
			gotStep := c.DaYun.Steps[0].Gan.String() + c.DaYun.Steps[0].Zhi.String()
			if gotStep != gc.DaYun.Steps[0] {
				t.Errorf("大运首步 = %s, want %s", gotStep, gc.DaYun.Steps[0])
			}

			// 三元（命宫/身宫/胎元）
			mg := fc.SanYuan.MingGong.Gan.String() + fc.SanYuan.MingGong.Zhi.String()
			sg := fc.SanYuan.ShenGong.Gan.String() + fc.SanYuan.ShenGong.Zhi.String()
			ty := fc.SanYuan.TaiYuan.Gan.String() + fc.SanYuan.TaiYuan.Zhi.String()
			if mg != gc.SanYuan.MingGong {
				t.Errorf("命宫 = %s, want %s", mg, gc.SanYuan.MingGong)
			}
			if sg != gc.SanYuan.ShenGong {
				t.Errorf("身宫 = %s, want %s", sg, gc.SanYuan.ShenGong)
			}
			if ty != gc.SanYuan.TaiYuan {
				t.Errorf("胎元 = %s, want %s", ty, gc.SanYuan.TaiYuan)
			}
		})
	}
}
