package agent

import (
	"context"
	"encoding/json"
	"errors"
	"testing"
)

func TestNewRPCRegistry_Count(t *testing.T) {
	reg := NewRPCRegistry()
	// 33 external methods (+ rpc.discover generated by OpenRPCDocument)
	if got := len(reg.names); got != 32 {
		t.Errorf("expected 33 methods, got %d", got)
	}
}

func TestNewRPCRegistry_KeyMethods(t *testing.T) {
	reg := NewRPCRegistry()
	expected := []string{
		"bazi.chart", "bazi.yongshen",
		"bazi.bond", "bazi.liunian", "bazi.liuyue", "bazi.liuri", "bazi.liushi",
		"bazi.xiaoyun",
		"ziwei.chart", "ziwei.daxian", "ziwei.liunian", "ziwei.liuyue", "ziwei.liuri", "ziwei.bond",
		"qimen.chart",
		"qiming.char", "qiming.pick", "qiming.build", "qiming.check",
		"bazhai.chart", "bazhai.layout",
		"xuankong.chart", "xuankong.liunian",
		"liuyao.qigua", "liuyao.chart",
		"huangli.days",
		"tianwen.time", "time.now", "city",
	}
	for _, name := range expected {
		m, ok := reg.methods[name]
		if !ok {
			t.Errorf("missing method: %s", name)
			continue
		}
		if m.Handler == nil {
			t.Errorf("method %s has nil handler", name)
		}
		if m.Description == "" {
			t.Errorf("method %s has empty description", name)
		}
	}
}

func TestNewRPCRegistry_MethodNotFound(t *testing.T) {
	reg := NewRPCRegistry()
	_, err := reg.Execute(context.TODO(), "nonexistent.method", nil)
	if err == nil {
		t.Fatal("expected error for nonexistent method")
	}
	var rpcErr *RPCError
	if !asError(t, err, &rpcErr) {
		t.Fatalf("expected *RPCError, got %T", err)
	}
	if rpcErr.Code != -32601 {
		t.Errorf("expected code -32601, got %d", rpcErr.Code)
	}
}

func TestOpenRPCDocument_Structure(t *testing.T) {
	reg := NewRPCRegistry()
	doc := reg.OpenRPCDocument()

	var parsed struct {
		OpenRPC string `json:"openrpc"`
		Info    struct {
			Title   string `json:"title"`
			Version string `json:"version"`
		} `json:"info"`
		Methods []json.RawMessage `json:"methods"`
	}
	if err := json.Unmarshal(doc, &parsed); err != nil {
		t.Fatalf("unmarshal OpenRPC doc: %v", err)
	}
	if parsed.OpenRPC != "1.4.1" {
		t.Errorf("openrpc version = %q, want 1.4.1", parsed.OpenRPC)
	}
	if parsed.Info.Title != "liki.hk JSON-RPC API" {
		t.Errorf("title = %q", parsed.Info.Title)
	}
	// 33 external + rpc.discover
	if got := len(parsed.Methods); got != 33 {
		t.Errorf("expected 33 methods in OpenRPC doc (32 + rpc.discover), got %d", got)
	}
}

// asError is a generic helper for errors.As.
func asError[T error](t *testing.T, err error, target *T) bool {
	t.Helper()
	return errors.As(err, target)
}
